import React from 'react';
import ReactMarkdown from 'react-markdown';
import { AlertTriangle, CheckCircle, FileCheck, Eye, Download } from 'lucide-react';
import remarkGfm from 'remark-gfm';

interface OutputDashboardProps {
  report: string;
}

export const OutputDashboard: React.FC<OutputDashboardProps> = ({ report }) => {
  if (!report) return null;

  return (
    <div className="bg-slate-850 rounded-xl border border-slate-700 shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-slate-800/50 p-4 border-b border-slate-700 flex justify-between items-center">
        <h3 className="text-white font-semibold flex items-center">
          <FileCheck className="w-5 h-5 mr-2 text-emerald-400" />
          Audit Dashboard Result
        </h3>
        <div className="flex space-x-2">
            <button className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-300 px-3 py-1.5 rounded-md border border-slate-600 transition-colors flex items-center">
                <Download className="w-3 h-3 mr-1" /> Export PDF
            </button>
        </div>
      </div>
      
      <div className="p-8 markdown-body text-slate-300 leading-relaxed">
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({node, ...props}) => {
                const text = props.children?.toString() || '';
                let icon = <Eye className="w-5 h-5 mr-2" />;
                let colorClass = "text-white border-b-2 border-slate-700 pb-2 mb-4 mt-6 uppercase tracking-wider text-sm font-bold flex items-center";
                
                if (text.includes("RISK SEVERITY")) {
                    colorClass += " text-red-400 border-red-900/50";
                    icon = <AlertTriangle className="w-5 h-5 mr-2 text-red-500" />;
                } else if (text.includes("COMPLIANCE VERDICT")) {
                     colorClass += " text-blue-400 border-blue-900/50";
                     icon = <CheckCircle className="w-5 h-5 mr-2 text-blue-500" />;
                }

                return <h1 className={colorClass}>{icon}{props.children}</h1>
            },
            h2: ({node, ...props}) => <h2 className="text-slate-100 font-semibold mt-4 mb-2 text-lg" {...props} />,
            p: ({node, ...props}) => <p className="mb-4 text-slate-300" {...props} />,
            ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-4 space-y-1 text-slate-300" {...props} />,
            li: ({node, ...props}) => <li className="pl-1" {...props} />,
            strong: ({node, ...props}) => <strong className="font-bold text-white bg-white/5 px-1 rounded" {...props} />,
          }}
        >
          {report}
        </ReactMarkdown>
      </div>

      <div className="bg-slate-900/50 p-4 border-t border-slate-700 text-center">
         <p className="text-xs text-slate-500 font-mono">
           Generated by Gemini 2.5 Flash • Guardian Ledger Ethical Engine • {new Date().toLocaleDateString()}
         </p>
      </div>
    </div>
  );
};
